# Required powershell
version: "3"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  build:dev: npm run dev
  build: npm run build
  watch: watchexec --no-vcs-ignore --exts "js,json,css" cp main.js styles.css manifest.json /mnt/c/Users/syoum/work/minerva/.obsidian/plugins/various-complements/

  init:
    desc: Install dependencies
    cmds:
      - npm install

  dev:
    desc: Build and copy files when they are updated.
    deps:
      - build:dev
      - watch

  test:
    desc: Unit tests
    cmds:
      - npm test

  test:watch:
    desc: Unit tests --watch
    cmds:
      - npm test -- --watch

  ci:
    desc: For CI
    cmds:
      - task: init
      - task: build
      - task: test

  release:
    desc: |
      Build
          ∟ [Ex] task release VERSION=1.2.3
          ∟ [Ex] task release VERSION=1.2.3-beta
    deps:
      - ci
    cmds:
      - npm version {{.VERSION}}
      - task: ci
      - git push --tags
      - git push
    preconditions:
      - sh: "[ {{.VERSION}} != '' ]"
        msg: "VERSION is required."
