name: "Tests"

on:
  push:
    paths:
      - ".github/**/*"
      - "src/*"
      - "src/**/*"
      - "*.js"
      - "*.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: corepack enable
      - run: pnpm run ci
